# name: Build and Deploy
# on: [push]
# permissions:
#   contents: write
# jobs:
#   build-and-deploy:
#     concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout 🛎️
#         uses: actions/checkout@v3

#       - name: 🏗 Setup pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8

#       - name: 🏗 Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: pnpm

#       - name: 🗂️ Install dependencies
#         run: pnpm i

#       - name: 🔨 Build
#         run: pnpm build
#         env:
#           VITE_FIREBASE_API_KEY: ${{ env.VITE_FIREBASE_API_KEY }}
#           VITE_FIREBASE_AUTH_DOMAIN: ${{ env.VITE_FIREBASE_AUTH_DOMAIN }}
#           VITE_FIREBASE_PROJECT_ID: ${{ env.VITE_FIREBASE_PROJECT_ID }}
#           VITE_FIREBASE_STORAGE_BUCKET: ${{ env.VITE_FIREBASE_STORAGE_BUCKET }}
#           VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ env.VITE_FIREBASE_MESSAGING_SENDER_ID }}
#           VITE_FIREBASE_APP_ID: ${{ env.VITE_FIREBASE_APP_ID }}
#           VITE_FIREBASE_MEASUREMENT_ID: ${{ env.VITE_FIREBASE_MEASUREMENT_ID }}
#           VITE_SUPABASE_API_KEY: ${{ env.VITE_SUPABASE_API_KEY }}

#       - name: Store variables
#         run: |
#           echo ${{ secrets.VITE_FIREBASE_API_KEY }}

#       - name: Deploy 🚀
#         uses: JamesIves/github-pages-deploy-action@v4
#         with:
#           folder: dist # The folder the action should deploy.

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 🗂️ Install dependencies
        run: pnpm i

      - name: Build project
        run: pnpm build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist